### ISSUE TITLE
请教个Mac下截屏权限问题

### ISSUE THREAD

**Issue by summerCol** [XMuli/FlippedPackage#2]
我在mac下调用QPixmap::grabWindow()获取截屏图片，通过QtCreator运行可以捕获到整个屏幕的完整截图；手动自己双击运行该程序只能截取到屏幕的背景以及该Qt程序的窗口。（并且MacOS下该Qt程序已经在“系统偏好设置”的“安全性与隐私”的“屏幕录制”中授权了还是每次截屏都会再弹框提示要再去“系统偏好设置”中设置，而且只能截取到桌面背景图和Qt程序窗口自身），想请问下之前你做这个截图工具的时候mac下是怎么解决截图权限问题才能获取到截图时桌面的完整截图？thanks.

**Comment by XMuli** [comment]
在“屏幕录制”中
**1. 先删除旧的 此程序**
2. 重新添加此程序的权限即可
