### ISSUE TITLE
全屏截图和延时截图这两个快捷键是不是搞反了？

### ISSUE THREAD

**Issue by HorrZzz** [XMuli/FlippedPackage#3]
设置里默认 全屏截图F7   延时截图F8。
实际使用中这两个快捷键貌似是反着来的

**Comment by XMuli** [comment]
已复现，感谢反馈，新版本会修复

**Comment by XMuli** [comment]
已顺带在新的架构和 UI 中已修复，可下载体验；

官网：[https://sunny.xmuli.tech](https://sunny.xmuli.tech)
Release: [https://github.com/XMuli/SunnyPages/releases](https://github.com/XMuli/SunnyPages/releases)
